application:
  name: jira
  createNamespace: ###ZARF_VAR_JIRA_CREATE_NAMESPACE###
  namespace: jira
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/community/jira.git
  ref:
    # renovate: datasource=gitlab-tags depName=big-bang/product/community/jira versioning=loose registryUrl=https://repo1.dso.mil
    tag: 1.16.5-bb.0
  dependsOn:
    ###ZARF_VAR_JIRA_DEPENDS_ON###
  baseValues:
    ingress:
      nginx: false
    proxyName: jira.###ZARF_VAR_DOMAIN###
    domain: ###ZARF_VAR_DOMAIN###
    istio:
      enabled: true
      jira:
        gateways:
          - istio-system/tenant
    jira:
      resources:
        container:
          requests:
            cpu: "100m"
            memory: "2Gi"
          limits:
            cpu: "10"
            memory: "6Gi"
        jvm:
          maxHeap: "4g"
      additionalEnvironmentVariables:
        - name: ATL_DB_TYPE
          value: "postgres72"
        - name: ATL_DB_DRIVER
          value: "org.postgresql.Driver"
        - name: ATL_JDBC_URL
          value: "jdbc:postgresql://jira-postgres.jira.svc.cluster.local:5432/jiradb"
        - name: ATL_JDBC_USER
          value: ###ZARF_VAR_JIRA_DB_USERNAME###
        - name: ATL_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "jira-postgres"
              key: "password"
    volumes:
      localHome:
        persistentVolumeClaim:
          create: true
          # storageClassName: your-storage-class-here
          resources:
            requests:
              storage: 1Gi
    # When istio injected, add an annotation with the istio version to the manager pods only
    podAnnotations:
      bigbang.dev/istioVersion: ###ZARF_VAR_ISTIO_VERSION###
    networkPolicies:
      enabled: true
      ingressLabels:
        app: tenant-ingressgateway
      controlPlaneCidr: 0.0.0.0/0
