apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: jira-postgres-host-path-exception
  namespace: jira-db
spec:
  exceptions:
  - policyName: restrict-host-path-write
    ruleNames:
    - require-readonly-hostpath
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - jira-db
        names:
        - postgresql-0
