apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: jira-postgres-non-root-group-exception
  namespace: jira-db
spec:
  exceptions:
  - policyName: require-non-root-group
    ruleNames:
    - run-as-group
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - jira-db
        names:
        - postgresql-0
