apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: jira-postgres-registry-exception
  namespace: jira-db
spec:
  exceptions:
  - policyName: restrict-image-registries
    ruleNames:
    - validate-registries
    - autogen-validate-registries
  match:
    any:
    - resources:
        kinds:
        - StatefulSet
        namespaces:
        - jira-db
        names:
        - postgresql
